version: "3.8"

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: task-tracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_tracker
    ports:
      - "5433:5432"